# Generated by Django 5.0.3 on 2024-03-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_tag_remove_product_size_alter_category_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='products', to='product.tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='text',
            field=models.CharField(max_length=200),
        ),
    ]
